### ISSUE TITLE
Has the config path changed?

### ISSUE THREAD

**Issue by philippeowagner** [3bot/3bot-worker#10]
(www)root@host:/server/web/example.ch/www# threebot-worker start
    No configfile found in: '/server/web/example.ch/www/3bot/config.ini'
    ----
    Creating basic configfile in '/server/web/example.ch/www/3bot/config.ini'
    ----
    Enter PORT: _

Wasn't it in the root of the virtualenv?!

**Comment by walterrenner** [comment]
maybe this is the case: https://github.com/3bot/3bot-worker/blob/master/threebot_worker/threebot-worker#L19?

**Comment by philippeowagner** [comment]
Okay, thanks @walterrenner. I will symlink in this case.
