### ISSUE TITLE
Starting the worker creates a ``./3bot/config.ini/`` directory

### ISSUE THREAD

**Issue by philippeowagner** [3bot/3bot-worker#9]
Furthermore the ``config.ini`` is ignored.

Versions installed: 
* threebot-crypto==1.0.16
* threebot-worker==0.1.0

**Comment by walterrenner** [comment]
@philippeowagner, this should be fixed in v0.1.1
i've pushed the release to the PyPI

**Comment by philippeowagner** [comment]
Thanks @walterrenner
